### ISSUE TITLE
Clean up vscode settings

### ISSUE THREAD

**Issue by magdapoppins** [TorstenDittmann/OmniaWrite#118]
I request that for example the font family setting and other unnecessary settings in the `.vscode` folder are removed, since they are unnecessary and make the development process hard since it's very difficult to see the text when those styles kick in.

**Comment by TorstenDittmann** [comment]
That is probably due to the fact, that you are missing the `JetBrains Mono` font. But yeah, you are right. These files are leftovers from a time where only I worked on OmniaWrite.

Since the settings are based purely on personal taste, I think they don't belong in that repository anymore. Also the extensions file with suggested extensions can disappear, because they are only optional.

If you want, feel free to create a PR deleting the `.vscode` folder and add it to the `.gitignore` 👍

**Comment by magdapoppins** [comment]
Ah, you're probably right. Will make a pr!

**Comment by TorstenDittmann** [comment]
Merged 🥳
